### ISSUE TITLE
Running the SDK on Visual Studio C++ 2015

### ISSUE THREAD

**Issue by axg596** [Affectiva/developerportal#70]
I was unable to open any of the files related to the SDK on Visual Studio C++. 

When debugging PhotoDetector\* detector = new PhotoDetector(2); it returned an error which pointed out that it was unable to convert from a \* datatype to a regular datatype. Since no pointers were used, I am stuck on how to move forward.

**Comment by umangmehta12** [comment]
Hi,
 I would suggest trying out the [cpp-sdk-samples](https://github.com/Affectiva/cpp-sdk-samples). This sample app has all the project configuration set. You can clone the project and follow the precise instructions in the [README](https://github.com/Affectiva/cpp-sdk-samples#sample-apps-for-affdex-sdk-for-windows-and-linux).

Here is the link to the documentation to our [Windows ( C++ ) SDK](http://developer.affectiva.com/pages/platforms/v3_1/cpp/classdocs/affdex-native/index.html).

To answer your question:
The SDK consists an include directory with the header files, the debug and release version of affdex-native, Affdex and opencv dll's, the class documentation for the C++ Platform and the data directory. You will have to link `affdex-native.lib` to your-project>Properties>Linker>Input>Additonal Dependencies.
You will also have to add the include directory under your-project>Properties>C/C++>General>Additional Include Directories.You will also have to point to the bin and the release directories when compiling your project.

**Comment by umangmehta12** [comment]
I am closing this issue since I haven't heard back from @axg596
